# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: The Vault
author: "Munchk1n"
email: "<email>"
description: A vault of knowledge about def/offensive info
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# ------------------------------------------------------------------------------
# Custom settings
# ------------------------------------------------------------------------------
# Useful links
github_username: "ST3G4N05"
facebook_username: "<facebook_username>"
twitter_username: "<twitter_username>"
linkedin_id: "<linkedin_id>"

# Theme
# theme: jekyll-theme-potato-hacker                 # Uncomment this
remote_theme: luxedo/jekyll-theme-potato-hacker   # Or this
theme_repository: "https://github.com/luxedo/jekyll-theme-potato-hacker"
theme_base: "dark"       # Theme palette (light | dark)
theme_switch: on         # Show color switch (on | off)

# Extra settings
blog: on                 # Show blog tag and post list (on | off)
avatar: on               # Show avatar (on | off)
avatar_image: "assets/img/avatar.jpg"
avatar_description: "Let's play Munchkin"
highlighter_theme: gruvbox  # Theme of the syntax_highlighter [base16 |
                            # colorful | github | gruvbox | molokai |
                            # monokai | pastie | thankful_eyes | tulip ]
toolbar_priority:        # Order of the items in the toolbar (except for blog and home)
  - Blue Team
  - Red Team
  - Recursos
  - How to...  #menu para Howto
  
  

# Collections

collections:
  dropdown:
    output: true
  items:
    output: true
##Added new items for drop menu
# Configuración de los dropdowns y items
dropdown:
# - title: "Blue Team"
#    dropdown: "Blue Team"
#    subitems:
#      - title: "SOC Analyst"
#        subitems:
#          - title: "Pyramid of Pain"
#            url: "/blue-team/soc-analyst/pyramid-of-pain/"
#          - title: "Other Theory"
#            url: "/blue-team/soc-analyst/other-theory/"
#      - title: "Log Analysis"
#        url: "/blue-team/log-analysis/"
#      - title: "Threat Detection"
#        url: "/blue-team/threat-detection/"

- title: "Red Team"
    dropdown: "Red Team"
    subitems:
      - title: "Recon"
        url: "/red-team/recon/"
      - title: "Enumeration"
        url: "/red-team/enumeration/"

  - title: "Blue Team"
    dropdown: "Blue Team"
    subitems:
      - title: "SOC Analyst"
        url: "/blue-team/soc-analyst/"
        subitems:
          - title: "Log Analysis"
            url: "/blue-team/log-analysis/"
          - title: "Networking"
            url: "/blue-team/networking/"
      - title: "Digital Forensics"
        url: "/blue-team/digital-forensics/"
        subitems:
          - 
      - title: "Reversing"
        url: "/blue-team/reversing/"
        subitems: 
          - 

  
# ------------------------------------------------------------------------------


# Build settings
excerpt_separator: "<!--more-->"
markdown: kramdown
highlighter: green    #rouge
kramdown:
  input: GFM
  syntax_highlighter: green    #rouge
exclude:
  - Gemfile
  - Gemfile.lock
